Controllers/System/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using CLGE_CORE.Models;
using IdentityServer4.EntityFramework.Entities;
using IdentityServer4.EntityFramework.Interfaces;
using IdentityServer4.EntityFramework.Mappers;
using IdentityServer4.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IdsServer {
  [Authorize]
  public class SystemController : Controller {

    // ILogger<SystemController> _logger;

    // public SystemController(ILogger<SystemController> logger)
    // {
    //   _logger = logger;
    // }
    private readonly IConfigurationDbContext _configDbContext;
    public SystemController (IConfigurationDbContext configDbContext) {

      _configDbContext = configDbContext;
    }
    public IActionResult Index () {
      var clients = _configDbContext.Clients.ToList ();
      ViewBag.clients = clients;
      return View ();
    }

    public IActionResult Modules (int? clientId) {
      //TODO: Implement Realistic Implementation
      List<ClientProperty> clientProperties = new List<ClientProperty> ();
      var clientApp = _configDbContext.Clients.Include ("Properties").Where (c => c.Id.Equals ((int) clientId)).FirstOrDefault ();

      if (clientApp.Properties != null) { clientProperties.AddRange (clientApp.Properties); }

      ViewBag.systemName = clientApp.ClientName;
      ViewBag.clientId = clientApp.Id;
      return View (clientProperties);
    }

    public IActionResult NewModule (int? clientId) {
      //TODO: Implement Realistic Implementation
      var clientApp = _configDbContext.Clients.Where (c => c.Id.Equals ((int) clientId)).FirstOrDefault ();
      ViewBag.ClientId = clientId;
      ViewBag.systemName = clientApp.ClientName;
      return View ();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult NewModule (CLGE_CORE.Models.ModuleViewModel property, int? clientId) {
      if (ModelState.IsValid) {

        var clientApp = _configDbContext.Clients.Find (clientId);
        clientApp.Properties = new List<ClientProperty> ();
        clientApp.Properties.Add (new ClientProperty{
           Key=property.Key,Value=property.Value

        });
        _configDbContext.SaveChanges ();

      }

      //TODO: Implement Realistic Implementation
      return RedirectToAction ("Modules", new { clientId = clientId });
    }
public IActionResult UpdateModule (int? clientId,int? Id) {
      //TODO: Implement Realistic Implementation
     var clientApp= _configDbContext.Clients.Include("Properties").Where (c => c.Id.Equals ((int) clientId)).FirstOrDefault ();
     if(clientApp!=null){
        var clientProps = clientApp.Properties;
        var module=clientProps.Find(m=>m.Id.Equals(Id));
        var moduleViewModel= new CLGE_CORE.Models.ModuleViewModel{
          Id=module.Id,Key=module.Key,Value=module.Value
        };
        ViewBag.ClientId = clientId;
        ViewBag.systemName = clientApp.ClientName;
        return View (moduleViewModel);
     }
      return NotFound();

    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult UpdateModule (CLGE_CORE.Models.ModuleViewModel property, int? clientId) {
      if (ModelState.IsValid) {
       var clientApp= _configDbContext.Clients.Include("Properties").Where (c => c.Id.Equals ((int) clientId)).FirstOrDefault ();
        
        var currentPop=clientApp.Properties.Find(cp=>cp.Id.Equals(property.Id));
        currentPop.Key=property.Key;
        currentPop.Value=property.Value;
        
        _configDbContext.SaveChanges ();
        
        return RedirectToAction ("Modules", new { clientId = clientId });
      }
    return View(property);
      //TODO: Implement Realistic Implementation
      
    }
    public IActionResult RegisterSystem () {
      //TODO: Implement Realistic Implementation
      return View ();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult RegisterSystem (SystemViewModel systemViewModel) {
      if (ModelState.IsValid) {

        var client = CreateNewClient (systemViewModel).ToEntity ();

        _configDbContext.Clients.Add (client);
        _configDbContext.SaveChanges ();

        if (systemViewModel.Configure) {
          return RedirectToAction ("UpdateDetails", new { clientId = client.Id });
        } else {
          return RedirectToAction ("Index");
        }
      }

      //TODO: Implement Realistic Implementation

      return View (systemViewModel);
    }
    public IActionResult UpdateDetails (int? clientId) {
      //TODO: Implement Realistic Implementation
      var clientApp = _configDbContext.Clients.Find (clientId);
      var systemViewModel = new SystemViewModel {
        Id = clientApp.Id, ClientUri = clientApp.ClientUri, SystemName = clientApp.ClientName,
        Description = clientApp.Description

      };
      ViewBag.clientId = clientId;
      ViewBag.systemName = clientApp.ClientName;
      return View (systemViewModel);
    }

    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public IActionResult UpdateDetails (SystemViewModel systemViewModel) {
      //TODO: Implement Realistic Implementation
      if (ModelState.IsValid) {
        var clientApp = _configDbContext.Clients.Find (systemViewModel.Id);

        clientApp.ClientUri = systemViewModel.ClientUri;
        clientApp.ClientName = systemViewModel.SystemName;
        clientApp.Description = systemViewModel.Description;
        _configDbContext.Clients.Update (clientApp);
        _configDbContext.SaveChanges ();
        ViewBag.clientId = systemViewModel.Id;
        ViewBag.systemName = clientApp.ClientName;
        return RedirectToAction ("Index");
      }
      return View (systemViewModel);

    }
    private IdentityServer4.Models.Client CreateNewClient (SystemViewModel systemViewModel) {

      var client = new IdentityServer4.Models.Client {
        ClientId = Guid.NewGuid ().ToString (),
        ClientName = systemViewModel.SystemName,
        AllowedGrantTypes = GrantTypes.Hybrid,
        ClientUri = systemViewModel.ClientUri,
        Description = systemViewModel.Description,
        ClientSecrets = {
        new IdentityServer4.Models.Secret ("secret".Sha256 ())
        },

        RedirectUris = { systemViewModel.ClientUri + "/signin-oidc" },
        PostLogoutRedirectUris = { systemViewModel.ClientUri + "/signout-callback-oidc" },

        AllowedScopes = {
        IdentityServer4.IdentityServerConstants.StandardScopes.OpenId,
        IdentityServer4.IdentityServerConstants.StandardScopes.Profile,

        "api1",
        "access.profile",
        "role",
        "token"
        },

        AllowOfflineAccess = true,
        AllowAccessTokensViaBrowser = true
      };

      return client;
    }
  }
}

Controllers/User/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CLGE_CORE.Models;
using IdentityModel;
using IdentityServer4.EntityFramework.Entities;
using IdentityServer4.EntityFramework.Interfaces;
using IdsServer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
//using UserController.Models;

namespace IdsServer {
  [Authorize]
  public class UserController : Controller {
    private readonly RoleManager<ApplicationRole> _roleMager;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IConfigurationDbContext _configDbContext;
    private readonly IPersistedGrantDbContext _persistedDbContext;

    //  private readonly UserStore<ApplicationUser> _userStore;
    public UserController (UserManager<ApplicationUser> userManager, IConfigurationDbContext configDbContext,
      IPersistedGrantDbContext persistedDbContext, RoleManager<ApplicationRole> roleMager) {

      _userManager = userManager;
      _configDbContext = configDbContext;
      _persistedDbContext = persistedDbContext;
      _roleMager = roleMager;
    }
    public async Task<IActionResult> Index () {
      //TODO: Implement Realistic Implementation
      //TODO: Implement Realistic Implementation
      var recordList = await _userManager.Users.ToListAsync ();
      ViewBag.userList = recordList;
      return View ();
    }
    public async Task<IActionResult> Register () {
      //TODO: Implement Realistic Implementation

      await Task.Yield ();
      return View ();
    }
    // GET api/user

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Register ([Bind ("FirstName,LastName,UserId,Password,ConfirmPassword,Configure")] RegisterUserViewModel userViewModel) {
      //TODO: Implement Realistic Implementation
      IActionResult ActionResult = RedirectToAction ("Index");
      if (ModelState.IsValid) {

        var user = new ApplicationUser {
          UserName = userViewModel.UserId, FirstName = userViewModel.FirstName, LastName = userViewModel.LastName,
        };
        var clientList = new List<AppUserClient> ();

        var result = await _userManager.CreateAsync (user, userViewModel.Password);

        if (result.Succeeded) {
          if (userViewModel.Configure) {

            return RedirectToAction ("Details", new { Id = user.Id });
          } else {

            return RedirectToAction ("Index");
          }

        } else {
          ViewBag.message = result.Errors.FirstOrDefault ().Description;
          // ActionResult = View (user);

          // return BadRequest();
        }

      }

      return View (userViewModel);

    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update ([Bind ("FirstName,LastName,UserName,Id")] ApplicationUser user) {
      //TODO: Implement Realistic Implementation
      
      var u = await _userManager.FindByIdAsync (user.Id.ToString());
      u.FirstName = user.FirstName;
      u.LastName = user.LastName;
      u.UserName = user.UserName;

      var result = await _userManager.UpdateAsync (u);

      return RedirectToAction ("Index");

    }
    public async Task<IActionResult> Details (int? Id) {
      //TODO: Implement Realistic Implementation
      var appUser = await _userManager.Users.Where (u => u.Id.Equals ((int) Id)).FirstOrDefaultAsync ();
      ViewBag.header=appUser.UserName;
      ViewBag.tabId = "details";

      return View (appUser);
    }
    public async Task<IActionResult> Roles () {
      await Task.Yield ();
      ViewBag.tabId = "roles";

      return View ();
    }
  //   [HttpGet("[controller]/[action]/{id?}/{delete?}")]
    public async Task<IActionResult> Applications (int? Id, bool? delete=false,int? selecteditem=0) {
      //TODO: Implement Realistic Implementation
       if(delete.HasValue){
         ViewBag.delete=delete;
         ViewBag.selecteditem=selecteditem;
       }else{ViewBag.delete=false;}
       

       ViewBag.Id=Id;
    // if(delete.HasValue){
        
    //      ViewBag.selectedItem=selectedItem;
    // }
    
    
      var appUser = await _userManager.Users.Include (c => c.Clients).FirstAsync (u => u.Id.Equals ((int) Id));
      ViewBag.header=appUser.UserName;
      List<Client> clientList = new List<Client> ();

      foreach (var item in appUser.Clients) {
        clientList.Add (_configDbContext.Clients.Find (item.ClientId));
      }

      // await Task.Yield();
      ViewBag.tabId = "application";

      return View (clientList);
    }

    [HttpGet]
    public async Task<IActionResult> AddUserApplication (int? Id) {
      //TODO: Implement Realistic Implementation
       ViewBag.header = "Assign Application to User";
      if (Id != null) {
        var appUser = await _userManager.Users.Include (c => c.Clients).FirstAsync (u => u.Id.Equals ((int) Id));
        var userAppList = appUser.Clients.ToList ();

        var applicationList = await _configDbContext.Clients.ToListAsync ();
        foreach (var item in userAppList)
        {
          
            applicationList.Remove(applicationList.FirstOrDefault(i=>i.Id.Equals(item.ClientId)));
        }
        
        
        IdsServer.Models.SystemSelectionViewModel selectionViewModel = new SystemSelectionViewModel ();

        foreach (var item in applicationList) {
          selectionViewModel.Application.Add (new Models.SystemEditorViewModel {
            Name = item.ClientName, ClientId = item.ClientId,
              Id = item.Id
          });
        }

        return View (selectionViewModel);
      }

      return NotFound();
     

    }
    
    public async Task<IActionResult> DeleteUserApplication (int? Id) {
     
      await Task.Yield();
      return RedirectToAction("Applications",new{Id=Id,delete=true});
    }

    
   
     public async Task<IActionResult> ExecuteDeleteUserApplication (int? Id,int? selecteditem) {
      
      var appUser = await _userManager.Users.Include (c => c.Clients).FirstAsync (u => u.Id.Equals ((int) Id));
      var currentItem =appUser.Clients.FirstOrDefault(c=>c.ClientId.Equals(selecteditem));
      appUser.Clients.Remove(currentItem);
      var roleList = _roleMager.Roles.Where (r => r.Client.Equals ((int) selecteditem)).ToList ();
      foreach (var item in roleList) {
        await _userManager.RemoveFromRoleAsync(appUser,item.Name);
      }
     
      // _roleMager.
      await _userManager.UpdateAsync(appUser);
      
      return RedirectToAction("Applications",new{Id=Id});
    }

    [HttpPost]
    public async Task<IActionResult> AssignApplication (IdsServer.Models.SystemSelectionViewModel selection, int Id) {
      //TODO: Implement Realistic Implementation
      ViewBag.header = "Assign Application to User";
      var appUser = await _userManager.Users.Include (c => c.Clients).FirstAsync (u => u.Id.Equals ((int) Id));

      PersistedGrant pg = new PersistedGrant ();

      foreach (var item in selection.Application) {

        //   pg.ClientId=item.Id.ToString();
        //  _persistedDbContext.PersistedGrants.Add(pg);
        if (item.Selected) {
          appUser.Clients.Add (new AppUserClient {
            ClientId = item.Id

          });
        }
      }
      await _userManager.UpdateAsync (appUser);
      //  await _persistedDbContext.SaveChangesAsync();
      //  _persistedDbContext.PersistedGrants.

      return RedirectToAction ("Applications", new { Id = Id });
    }

    public async Task<IActionResult> AddUserGroup () {
      //TODO: Implement Realistic Implementation
      await Task.Yield ();

      return View ();
    }
    public async Task<IActionResult> AddUserRole (int? clientId,int? Id) {
      //TODO: Implement Realistic Implementation
       var user = _userManager.FindByIdAsync (((int) Id).ToString ()).Result;
      ViewBag.ClientId = (int) clientId;
      var roleListViewModel = new List<RoleEditorViewModel> ();
      var roleList = _roleMager.Roles.Where (r => r.Client.Equals ((int) clientId)).ToList ();
      foreach (var item in roleList) {
        var role=new RoleEditorViewModel {
          Name = item.Name, Id = item.Id
            
        };
         role.Selected=_userManager.IsInRoleAsync(user,item.Name).Result;
       
        roleListViewModel.Add (role);
      }

      await Task.Yield ();

      return View (roleListViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> AddUserRole (List<RoleEditorViewModel> roles, int? Id) {
      var user = _userManager.FindByIdAsync (((int) Id).ToString ()).Result;

      foreach (var item in roles) {
        if (item.Selected) {

          await _userManager.AddToRoleAsync (user, item.Name);
          //  await  _userManager.AddClaimAsync(user, new Claim(ClaimTypes.Role, item.Name));
        }else{
           await _userManager.RemoveFromRoleAsync(user, item.Name);
        }

      }

      return RedirectToAction ("Applications", new { Id = Id });
    }

  }
}

Views/Shared/Redirect.cshtml
@model RedirectViewModel

<h1>You are now being returned to the application.</h1>
<p>Once complete, you may close this tab</p>

<meta http-equiv="refresh" content="0;url=@Model.RedirectUrl" data-url="@Model.RedirectUrl">
<script src="~/js/signin-redirect.js"></script>

Views/Shared/_Layout.cshtml
@{
   
    var action = ViewContext.RouteData.Values["Action"];
    var controller = ViewContext.RouteData.Values["Controller"];
    var Id = ViewContext.RouteData.Values["Id"];
    var clientId = ViewContext.RouteData.Values["clientId"];
    var tabId=ViewBag.tabId;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IdentityServer4</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
     <!-- <link rel="stylesheet" href="~/css/materia/bootstrap.css" /> -->
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" />
     <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
  
    @using IdentityServer4.Extensions
@{
    string name = null;
    if (!true.Equals(ViewData["signed-out"]))
    {
        name = Context.User?.GetDisplayName();
    }
}
    @if(User.IsAuthenticated()){
        <nav class="navbar navbar-expand-lg">
        
           
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                   
                    <span class="navbar-toggler-icon">

                        <i class="fas fa-bars"></i>

                    </span>
                </button>
 <div class="navbar-brand" style="padding=0" >
 
                    

                        <img class="icon-banner" src="~/images/bdoLogo.png" alt="BDO">
                       
                    
                   
                    
           
 </div>
    <div class="float-right">
        <h1>CLG</h1><h4 >Exchange <span ><strong>1.0.0</strong></span></h4>
                            
    </div>
 
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav  float-right">
                    <li class="nav-item active">
                        <a href="~/"  class="nav-link"> <i class="fas fa-home fa-4x"></i> Home </a>
                    </li>
                    <li class="nav-item">
                    <a asp-action="Index" asp-controller="User"  class="nav-link"> <i class="fas fa-users-cog fa-4x text-warning"></i> Users </a>
                    </li>
                    <li class="nav-item">
                    <a asp-controller="System" asp-action="Index"  class="nav-link"> <i class="fas fa-sitemap fa-4x"></i> Systems </a>
                    </li>
                        <li class="nav-item">
                    <a asp-controller="Home" asp-action="Logout" class="nav-link"> <i class="fas fa-sign-out-alt fa-4x"></i> Logout </a>
                    </li>
                        
                    </ul>
                    
                </div>
        </nav>
    }
 

<ol class="breadcrumb">
          <li class="breadcrumb-item"><a asp-controller="@controller" asp-action="Index" asp-route-clientId="@clientId">@controller</a></li>
          <li class="breadcrumb-item"><a asp-controller="@controller" asp-action="@action" asp-route-clientId="@clientId">@action</a></li>
          <li class='breadcrumb-item active @(Id==null? "d-none":string.Empty)'>Data</li>
        </ol>


    <div class="container-fluid">
        @RenderBody()
    </div>

   
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script>
        $(document).ready(function() {
            $('.input-validation-error').parents('.form-group').addClass('has-danger');
            $('.input-validation-error').addClass('text-danger is-invalid');
            

        });
    </script>
    @RenderSection("scripts", required: false)
    
</body>
</html>

Views/Shared/_SystemLayout.cshtml
@{
    Layout = "_Layout";
    string header=ViewBag.header==null?string.Empty:ViewBag.header;
   
}


<div class="card">
  <h2 class="card-header"> <i class="fa fa-sitemap"></i>  @ViewBag.systemName</h2>
  
  <div class="card-body">
      
                     <div class="container-fluid">
                      @RenderBody()
                  </div>
      <!-- <a asp-controller="System" asp-action="Index" class="btn float-right">Back</a> -->
      </div>
</div>

Views/Shared/_SystemTabedLayout.cshtml
@{
    Layout = "_SystemLayout";
    var action = ViewContext.RouteData.Values["Action"];
     var controller = ViewContext.RouteData.Values["Controller"];
         var Id = ViewContext.RouteData.Values["Id"];
         var v=ViewContext.RouteData.Values;
    var tabId=ViewBag.tabId;
}

        


              <ul class="nav nav-tabs">
                 <li class="nav-item">
                  <a class='nav-link @(controller.Equals("System") && action.Equals("UpdateDetails")  ? "active":string.Empty)' asp-controller="System" asp-action="UpdateDetails" asp-route-clientId="@ViewBag.clientId ">Details</a>
                </li>
                <li class="nav-item">
                  <a class='nav-link @(controller.Equals("System") && action.Equals("Modules")  ? "active":string.Empty)' asp-controller="System" asp-action="Modules" asp-route-clientId="@ViewBag.clientId ">Modules</a>
                </li>
                
                <!-- <li class="nav-item">
                  <a class='nav-link  @(action.Equals("Roles") ? "active":string.Empty)'  asp-action="Roles">Roles</a>
                </li> -->
                <li class="nav-item">
                  <a class='nav-link  @(controller.Equals("Role") ? "active":string.Empty)'   asp-action="Index" asp-controller="Role" asp-route-clientId="@ViewBag.clientId">Roles</a>
                </li>
                <!-- <li  class="nav-item">
                  <a class="nav-link disabled" href="#">Disabled</a>
                </li> -->
                
              </ul>
              <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade show active" id="@tabId">
                <div class="container-fluid">
                      @RenderBody()
                  </div>
                </div>
                
              </div>

Views/Shared/_TabbedLayout.cshtml
@{
    Layout = "_UserLayout";
    string action = ViewContext.RouteData.Values["Action"].ToString();
     var controller = ViewContext.RouteData.Values["Controller"].ToString();
         var Id = ViewContext.RouteData.Values["Id"];
         List<string> appActionList= new List<string>{"Applications","AddUserRole"};
    var tabId=ViewBag.tabId;
}

        


              <ul class="nav nav-tabs">
                <li class="nav-item">
                  <a class='nav-link @(action.Equals("Details") ? "active":string.Empty)'  asp-action="Details" asp-route-id="@Id">Details</a>
                </li>
                
                <!-- <li class="nav-item">
                  <a class='nav-link  @(action.Equals("Roles") ? "active":string.Empty)'  asp-action="Roles">Roles</a>
                </li> -->
                <li class="nav-item">
                  <a class='nav-link  @(appActionList.Contains(action) ? "active":string.Empty)'   asp-action="Applications"  asp-route-id="@Id" >Applications</a>
                </li>
                <!-- <li  class="nav-item">
                  <a class="nav-link disabled" href="#">Disabled</a>
                </li> -->
                
              </ul>
              <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade show active" id="@tabId">
                <div class="container-fluid">
                      @RenderBody()
                  </div>
                </div>
                
              </div>

Views/Shared/_UserLayout.cshtml
@{
    Layout = "_Layout";
    string header=ViewBag.header==null?string.Empty:ViewBag.header;
   
}


<div class="card border-light">
  <div class="card-header">
     <div id="" class="row">
           <h4><i id="" class="fa fa-user-cog text-primary"></i> @header</h4>
      </div>
  </div>
  <div class="card-body">
                     <div class="container-fluid">
                      @RenderBody()
                  </div>
      
      </div>
</div>

Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    


    <div class="row" ng-show="model.errorMessage">
                <div class="col-md-12 col-sm-12">
                    <div class="alert alert-danger">
                        <strong>Error</strong>
                        <div asp-validation-summary="All" class="danger">
                            
                        </div>
                    </div>
                </div>
    </div>
}